from graphs import *
from ordersAndDrivers import *
from driverPolicies import *
from collections import deque
import random

def maxItemLength(a):
    maxLen = 0
    rows = len(a)
    cols = len(a[0])
    for row in range(rows):
        for col in range(cols):
            maxLen = max(maxLen, len(str(a[row][col])))
    return maxLen

# https://www.kosbie.net/cmu/spring-21/15-112/notes/notes-2d-lists.html
def format2dList(a):
    if (a == []):
        return "[]"
    
    rows, cols = len(a), len(a[0])
    fieldWidth = maxItemLength(a)
    lines = []
    lines.append('[')
    for row in range(rows):
        line = ' [ '
        for col in range(cols):
            if (col > 0): line += ', '
            line += str(a[row][col]).rjust(fieldWidth)
        line += ' ]'
        if row < rows - 1:
            line += ','
        lines.append(line)
    lines.append(']')
    return '\n'.join(lines)

def genDropoff(randomMap, pickup, dropoffThreshold):
    availableDropoffs = []
    
    # BFS to get all available dropoffs within threshold
    q = deque([(pickup, 0)])
    visited = set()

    while q:
        currNode, currDur = q.popleft()

        if currNode not in visited:
            visited.add(currNode)

            for neighbor, dur in enumerate(randomMap.adjMatrix[currNode]):
                if dur != None:
                    totalDur = currDur + dur
                    if totalDur <= dropoffThreshold:
                        if neighbor != pickup:
                            availableDropoffs.append(neighbor)
                        q.append((neighbor, totalDur))

    if not availableDropoffs:
        print(f"ERROR: not enough dropoffs within the threshold {dropoffThreshold}")
        return
    
    # choose a random dropoff within the threshold
    return random.choice(availableDropoffs)

def getDeliverTime(randomMap, pickup, dropoff):
    pickupToDropOff = nx.shortest_path(randomMap.G, 
                    source=pickup, target=dropoff, weight = 'weight')
    totalTime = 0
    for i in range(1, len(pickupToDropOff)):
        currNode, prevNode = pickupToDropOff[i], pickupToDropOff[i-1]
        duration = randomMap.adjMatrix[currNode][prevNode]
        totalTime += duration

    return totalTime

def genTest(testNum, n, m, basePay, numDrivers, durationRange, pickupTimeRange, orderSpawnRate, totalMins, dropoffThreshold=20, deliverTimeWiggleRoom=0):
    randomMap = RandomGridLayout(n, m, n * m, durationRange)                               
    orderCount = 0
    numNodes = n * m 
    orderQueue = []
    policies = ['rateFocused', 'greedy', 'reputationFocused']
    driverBehaviors = [1.1, 1.0, 0.9]
    drivers = [(i, random.randint(0, numNodes-1), random.choice(policies), random.choice(driverBehaviors)) for i in range(0, numDrivers)]
    for minute in range(totalMins):
        if random.random() < orderSpawnRate:
            pickup = random.randint(0, numNodes-1)
            dropoff = genDropoff(randomMap, pickup, dropoffThreshold)
            if dropoff == None: # could not meet threshold, exit
                return                                                      
            start, end = pickupTimeRange
            pickupTime = minute + random.randint(start, end) 
            deliverTime = pickupTime
            # dont penalize twice 
            deliverTime += getDeliverTime(randomMap, pickup, dropoff) + deliverTimeWiggleRoom
            orderQueue.append((orderCount, pickup, dropoff, minute, pickupTime, deliverTime))
            orderCount += 1
    testFunction = \
    f'''
# TEST {testNum}
# LAYOUT: {n}x{m} GRID
# {numDrivers} DRIVERS, {totalMins//60} HOUR PERIOD
# FLAT RATE ${basePay}/order
# EDGE DURATIONS RANGE {durationRange}
# PICKUP TIME RANGE {pickupTimeRange}
# DELIVER TIME WIGGLE ROOM {deliverTimeWiggleRoom}
# DROPOFF THRESHOLD {dropoffThreshold}
# ACTIVE POLICIES: {policies}
def test{testNum}():
        n = {n}
        m = {m}
        basePay = {basePay} # total price will be calculated later when assigned to driver
        totalMins = {totalMins}
        adjMatrix = \\
        {format2dList(randomMap.adjMatrix)}
        map = GridLayout(n, m, n * m, adjMatrix)
        policyDict = {{ 'rateFocused' : rateFocused, 'greedy' : greedy, 'reputationFocused' : reputationFocused }}
        orderInfo = \\
        {orderQueue}
        driverInfo = \\
        {drivers}
        orderQueue = []
        drivers = []
        # INIT ORDERS
        for id, pickup, dropoff, releaseTime, pickupTime, deliverTime in orderInfo:
            orderQueue.append(Order(id, pickup, dropoff, releaseTime, pickupTime, deliverTime, basePay))
        # INIT DRIVERS
        for id, start, policy, driverBehavior in driverInfo:
            driverPolicy = DriverPolicy(policy, policyDict[policy])
            drivers.append(Driver(id, start, driverPolicy, driverBehavior))

        return map, orderQueue, totalMins, drivers, basePay'''
    return testFunction

# TEST 1
# LAYOUT: 8x8 GRID
# 13 DRIVERS, 6 HOUR PERIOD   
# FLAT RATE $5/order
# EDGE DURATIONS RANGE (5, 10)
# PICKUP TIME RANGE (15, 25)  
# DELIVER TIME WIGGLE ROOM 0  
# DROPOFF THRESHOLD 20
def test1():
        n = 8
        m = 8
        basePay = 5 # total price will be calculated later when assigned to driver
        totalMins = 360
        adjMatrix = \
        [
 [ None,   10, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [   10, None,    8, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None,    8, None,   10, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None,   10, None,    6, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None,    6, None,   10, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None,   10, None,    5, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None,    5, None,    6, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [    7, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None,    7, None, None, None, None, None, None,    7, None,   10, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None,    8, None, None, None, None, None, None,   10, None,    7, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None,    7, None, None, None, None, None, None,    7, None,   10, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None,    6, None, None, None, None, None, None,   10, None,    6, None, None, None, None, None, None,    7, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None,    9, None, None, None, None, None, None,    6, None,    6, None, None, None, None, None, None,    5, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None,    6, None, None, None, None, None, None,    6, None,    7, None, None, None, None, None, None,    6, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None,    5, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,    9, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None,    6, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None,   10, None,    6, None, None, None, None, None, None,    5, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None,    6, None,   10, None, None, None, None, None, None,    9, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None,   10, None,    8, None, None, None, None, None, None, 
   7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None,    8, None,    9, None, None, None, None, None, 
None,    5, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None,    9, None,    7, None, None, None, None, 
None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None,    7, None,   10, None, None, None, 
None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None,   10, None, None, None, None, 
None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    8, None, 
None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None,    8, None,    5, 
None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None,    5, None, 
  10, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None,   10, 
None,    6, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, 
   6, None,   10, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, 
None,   10, None,    5, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, 
None, None,    5, None,    6, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, 
None, None, None,    6, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, 
None, None, None, None, None, None,    5, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, 
None, None, None, None, None,    5, None,    5, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, 
None, None, None, None, None, None,    5, None,    8, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
   9, None, None, None, None, None, None,    8, None,    9, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None,    9, None, None, None, None, None, None,    9, None,    9, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None,    6, None, None, None, None, None, None,    9, None,    6, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None,    7, None, None, None, None, None, None,    6, None,    7, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None,    6, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None,    7, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None,    8, None, None, None, None, None, None,   10, None,    8, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None,    9, None, None, None, None, None, None,    8, None,    5, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None,    5, None,    5, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None,    5, None,    5, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None,    5, None,    5, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None,    5, None,    7, None, None, None, None, None, None,    
7, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None,    8, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None,    8, None,    9, None, None, None, None, None, None,    8, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None,    9, None,   10, None, None, None, None, None, None,    6, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None,   10, None,    5, None, None, None, None, None, None,    5, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None,    5, None,   10, None, None, None, None, None, None,    9, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None,   10, None,    
6, None, None, None, None, None, None,    9, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None,    6, None,    5, None, None, None, None, None, None,    5, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None,    
5, None, None, None, None, None, None, None, None,   10 ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None,    9, None,   10, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None,   10, None,    5, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None,    5, None,    5, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None,    5, None,   10, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None,   10, None,    7, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    
5, None, None, None, None, None, None,    7, None,    5 ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None,    5, None ]
]
        map = GridLayout(n, m, n * m, adjMatrix)
        policyDict = { 'rateFocused' : rateFocused, 'greedy' : greedy }
        orderInfo = \
        [(0, 16, 25, 3, 25, 39), (1, 26, 35, 15, 39, 53), (2, 11, 20, 16, 33, 48), (3, 10, 3, 17, 37, 51), (4, 0, 16, 22, 44, 61), (5, 2, 1, 24, 45, 53), (6, 51, 49, 25, 46, 65), (7, 42, 34, 26, 42, 51), (8, 38, 46, 29, 54, 63), (9, 12, 19, 32, 48, 63), (10, 17, 26, 39, 61, 71), (11, 15, 22, 40, 65, 78), (12, 9, 17, 44, 69, 74), (13, 20, 4, 49, 64, 77), (14, 30, 23, 53, 71, 82), (15, 17, 9, 55, 72, 77), (16, 39, 45, 57, 74, 92), (17, 33, 27, 58, 79, 99), (18, 27, 26, 62, 79, 89), (19, 44, 34, 65, 88, 106), (20, 8, 24, 69, 89, 105), (21, 47, 38, 70, 87, 103), (22, 29, 20, 80, 99, 114), (23, 29, 22, 85, 101, 113), (24, 5, 12, 87, 104, 119), (25, 47, 54, 
88, 108, 122), (26, 22, 7, 90, 113, 131), (27, 32, 26, 104, 126, 141), (28, 46, 37, 107, 131, 141), (29, 38, 22, 108, 124, 138), (30, 0, 9, 114, 135, 149), (31, 59, 
60, 115, 139, 144), (32, 2, 4, 116, 137, 153), (33, 13, 14, 118, 143, 149), (34, 20, 22, 122, 143, 159), (35, 59, 61, 123, 147, 162), (36, 8, 17, 125, 141, 153), (37, 27, 34, 132, 147, 163), (38, 51, 43, 133, 156, 164), (39, 13, 5, 142, 158, 167), (40, 42, 25, 146, 162, 181), (41, 14, 23, 149, 170, 186), (42, 27, 43, 154, 179, 193), (43, 53, 44, 156, 171, 182), (44, 17, 25, 159, 183, 188), (45, 52, 59, 164, 187, 197), (46, 61, 44, 173, 188, 208), (47, 34, 26, 177, 192, 198), (48, 3, 12, 178, 194, 206), (49, 16, 18, 180, 198, 214), (50, 5, 3, 181, 198, 214), (51, 10, 3, 182, 206, 220), (52, 51, 60, 184, 204, 214), (53, 14, 21, 191, 212, 223), (54, 18, 27, 192, 213, 230), (55, 3, 10, 193, 214, 228), (56, 22, 37, 195, 211, 229), (57, 50, 41, 206, 224, 240), (58, 27, 43, 210, 233, 247), (59, 58, 49, 217, 233, 248), (60, 9, 8, 221, 238, 245), (61, 35, 34, 225, 242, 250), (62, 58, 49, 228, 249, 264), (63, 0, 9, 229, 244, 258), (64, 62, 54, 230, 255, 260), (65, 62, 61, 232, 255, 262), (66, 8, 0, 241, 263, 270), (67, 7, 13, 243, 259, 277), (68, 4, 13, 244, 260, 272), (69, 17, 33, 245, 261, 271), (70, 7, 5, 263, 282, 293), (71, 19, 18, 264, 288, 
298), (72, 47, 39, 274, 298, 308), (73, 39, 55, 275, 292, 311), (74, 3, 11, 277, 297, 304), (75, 38, 44, 278, 297, 313), (76, 52, 61, 279, 294, 313), (77, 14, 5, 280, 297, 308), (78, 4, 5, 281, 301, 311), (79, 36, 37, 284, 307, 316), (80, 7, 23, 291, 312, 326), (81, 10, 19, 293, 308, 322), (82, 0, 8, 297, 313, 320), (83, 42, 34, 306, 325, 334), (84, 62, 63, 309, 331, 336), (85, 39, 37, 313, 336, 349), (86, 61, 55, 314, 332, 349), (87, 41, 34, 317, 334, 347), (88, 52, 51, 323, 346, 351), (89, 17, 8, 324, 342, 354), (90, 1, 17, 329, 347, 359), (91, 12, 11, 332, 348, 358), (92, 41, 32, 333, 351, 364), (93, 62, 45, 338, 354, 371), (94, 7, 6, 339, 363, 369), (95, 10, 9, 340, 364, 374), (96, 3, 12, 343, 363, 375), (97, 1, 9, 347, 367, 374), (98, 30, 45, 349, 366, 382), (99, 39, 29, 351, 374, 391), (100, 14, 30, 353, 370, 383)]
        driverInfo = \
        [(0, 2, 'rateFocused', 1.0), (1, 1, 'greedy', 1.1), (2, 51, 'rateFocused', 1.1), (3, 53, 'rateFocused', 1.0), (4, 1, 'rateFocused', 1.1), (5, 51, 'greedy', 1.1), (6, 11, 'greedy', 1.0), (7, 45, 'greedy', 1.0), (8, 60, 'greedy', 1.0), (9, 43, 'rateFocused', 1.0), (10, 47, 'rateFocused', 0.9), (11, 52, 'greedy', 1.1), (12, 40, 'rateFocused', 1.0)]
        orderQueue = []
        drivers = []
        # INIT ORDERS
        for id, pickup, dropoff, releaseTime, pickupTime, deliverTime in orderInfo:
            orderQueue.append(Order(id, pickup, dropoff, releaseTime, pickupTime, deliverTime, basePay))
        # INIT DRIVERS
        for id, start, policy, driverBehavior in driverInfo:
            driverPolicy = DriverPolicy(policy, policyDict[policy])
            drivers.append(Driver(id, start, driverPolicy, driverBehavior))

        return map, orderQueue, totalMins, drivers, basePay

# TEST 2
# LAYOUT: 10x10 GRID
# 15 DRIVERS, 6 HOUR PERIOD
# FLAT RATE $5/order
# EDGE DURATIONS RANGE (5, 10)
# PICKUP TIME RANGE (15, 25)
# DELIVER TIME WIGGLE ROOM 0
# DROPOFF THRESHOLD 20
# ACTIVE POLICIES: ['rateFocused', 'greedy', 'reputationFocused']
def test2():
        n = 10
        m = 10
        basePay = 5 # total price will be calculated later when assigned to driver
        totalMins = 360
        adjMatrix = \
        [
 [ None,    8, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [    8, None,    5, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None,    5, None,    9, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None,    9, None,    6, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None,    6, None,    8, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None,    8, None,    6, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None,    6, None,    7, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None,    7, None,    6, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None,    6, None,    5, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [   10, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None,    8, None, None, None, None, None, None, None, None,    8, None,    9, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None,    7, None, None, None, None, None, None, None, None,    9, None,    7, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None,    7, None, None, None, None, None, None, None, None,    7, None,   10, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None,   10, None, None, None, None, None, None, None, None,   10, None,    7, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None,   10, None, None, None, None, None, None, None, None,    7, None,    5, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    5, None,   10, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,   10, None,    7, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,    7, None,    5, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,    8, None,    6, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,    6, None,    8, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    8, None,    9, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    9, None,   10, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,   10, None,    7, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    7, None,    9, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None,    9, None,    5, None, None, None, None, None, None, None, None,  
  9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None,    5, None,    6, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    5, None,    7, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None,    7, None,    9, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,    9, None,   10, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,   10, None,    8, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,    8, None,    9, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    9, None,  
  7, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,    7, None,    7, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,  
  7, None,   10, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None,    6, None,    5, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None,    5, None,    7, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,    7, None,   10, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,   10, None,    5, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    5, None,    5, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,    5, None,    8, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,  
  7, None, None, None, None, None, None, None, None,    8, None,    6, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None,    6, None,    6, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,    9, None,    9, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,    9, None,    8, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    8, None,    7, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    7, None,    7, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None,    7, None,    5, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,    5, None,    7, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None,    7, None,   10, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None,   10, None,    9, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,   10, None,    8, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,    8, None,    6, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    6, None,    9, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,    9, None,   10, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,   10, None,    9, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None,    9, None,    8, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None,    8, None,    9, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    9, None,    6, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    9, None,    7, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    7, None,    9, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,    9, None,    7, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None,    7, None,    9, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    9, None,   10, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,   10, None,    8, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    8, None,    8, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,    8, None,    5, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    9, None,    5, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    5, None,    8, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    8, None,    9, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    9, None,    9, None, None, None, None, None, None, None, None,    5, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None,    9, None,    9, None, None, None, None, None, None, None, None,    8, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,    9, None,    9, None, None, None, None, None, None, None, None,    6, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    9, None,    5, None, None, None, None, None, None, None, None,    9, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,    5, None,    7, None, None, None, None, None, None, None, None,    6, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None,    7, None, None, None, None, None, None, None, None, None, None,    8 ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,    6, None,    8, None, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    8, None,   10, None, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,   10, None, None, None, None, None, None, None, None,   10, None,    5, None, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    5, None, None, None, None, None, None, None, None,    5, None,   10, None, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,   10, None,    7, None, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    7, None,    9, None, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    9, None, None, None, None, None, None, None, None,    9, None,    5, None ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    6, None, None, None, None, None, None, None, None,    5, None,    9 ],
 [ None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,    8, None, None, None, None, None, None, None, None,    9, None ]
]
        map = GridLayout(n, m, n * m, adjMatrix)
        policyDict = { 'rateFocused' : rateFocused, 'greedy' : greedy, 'reputationFocused' : reputationFocused }
        orderInfo = \
        [(0, 89, 79, 0, 25, 30), (1, 55, 56, 3, 19, 24), (2, 72, 82, 5, 20, 26), (3, 66, 55, 7, 31, 46), (4, 57, 58, 8, 30, 40), (5, 31, 21, 9, 28, 34), (6, 47, 57, 14, 37, 47), (7, 80, 81, 16, 33, 42), (8, 27, 16, 17, 41, 56), (9, 23, 14, 18, 40, 55), (10, 84, 74, 21, 44, 52), (11, 74, 84, 27, 49, 57), (12, 76, 85, 33, 49, 66), (13, 94, 83, 35, 58, 72), (14, 68, 66, 36, 59, 76), (15, 84, 73, 37, 54, 69), (16, 54, 64, 39, 56, 63), (17, 35, 46, 40, 
57, 68), (18, 73, 53, 42, 61, 76), (19, 34, 14, 45, 65, 80), (20, 11, 0, 46, 66, 82), (21, 62, 72, 50, 67, 73), (22, 58, 57, 51, 74, 84), (23, 23, 31, 53, 78, 98), (24, 29, 28, 56, 71, 77), (25, 75, 95, 66, 87, 102), (26, 83, 
74, 67, 85, 100), (27, 52, 72, 68, 89, 102), (28, 53, 64, 71, 89, 103), (29, 39, 37, 72, 93, 110), (30, 77, 75, 74, 95, 113), (31, 43, 34, 76, 95, 111), (32, 79, 89, 79, 101, 106), (33, 82, 71, 84, 103, 116), (34, 51, 41, 87, 
103, 112), (35, 24, 14, 94, 114, 120), (36, 52, 61, 95, 113, 128), (37, 47, 36, 97, 121, 135), (38, 91, 93, 98, 113, 131), (39, 23, 3, 99, 123, 136), (40, 41, 30, 107, 125, 136), (41, 66, 55, 114, 138, 153), (42, 64, 73, 115, 
138, 150), (43, 30, 50, 122, 146, 159), (44, 59, 48, 125, 143, 159), (45, 80, 70, 127, 142, 151), (46, 64, 54, 132, 151, 158), (47, 33, 34, 134, 152, 162), (48, 39, 37, 141, 161, 178), (49, 56, 36, 142, 159, 175), (50, 94, 83, 143, 162, 176), (51, 46, 47, 145, 167, 175), (52, 15, 35, 147, 166, 180), (53, 21, 2, 148, 170, 190), (54, 90, 82, 150, 165, 185), (55, 41, 52, 156, 177, 189), (56, 71, 72, 157, 174, 181), (57, 32, 31, 161, 186, 193), (58, 92, 84, 162, 184, 204), (59, 20, 30, 163, 186, 193), (60, 99, 88, 165, 183, 198), (61, 38, 29, 166, 186, 199), (62, 82, 71, 185, 209, 222), (63, 94, 93, 189, 212, 217), (64, 4, 13, 193, 211, 224), (65, 35, 46, 196, 211, 222), (66, 43, 53, 198, 215, 223), (67, 44, 64, 200, 215, 230), (68, 27, 37, 201, 225, 234), (69, 97, 88, 202, 224, 235), (70, 64, 94, 203, 227, 245), (71, 31, 20, 204, 220, 232), (72, 20, 50, 209, 227, 247), (73, 80, 90, 218, 241, 247), (74, 84, 74, 220, 236, 244), (75, 94, 83, 222, 242, 256), (76, 12, 0, 223, 238, 258), (77, 97, 87, 225, 244, 253), (78, 3, 13, 227, 247, 254), (79, 83, 92, 234, 256, 272), (80, 35, 25, 235, 259, 266), (81, 24, 14, 239, 255, 261), (82, 56, 65, 244, 260, 272), (83, 93, 92, 248, 266, 276), (84, 3, 1, 249, 268, 282), (85, 82, 72, 250, 270, 276), (86, 97, 99, 253, 272, 286), (87, 81, 92, 254, 272, 285), (88, 45, 64, 256, 277, 297), (89, 90, 81, 264, 287, 302), (90, 86, 87, 271, 296, 305), (91, 97, 77, 272, 292, 309), (92, 13, 24, 274, 294, 309), (93, 86, 77, 276, 298, 315), (94, 4, 16, 277, 292, 312), (95, 17, 26, 279, 297, 311), (96, 5, 14, 288, 311, 328), (97, 19, 28, 
291, 312, 327), (98, 37, 39, 296, 316, 333), (99, 68, 77, 298, 313, 330), (100, 55, 66, 304, 321, 336), (101, 54, 57, 306, 323, 342), (102, 76, 86, 311, 335, 344), (103, 35, 46, 312, 337, 348), (104, 28, 27, 313, 337, 342), (105, 90, 80, 321, 344, 350), (106, 44, 55, 322, 338, 353), (107, 4, 2, 324, 349, 364), (108, 87, 78, 336, 355, 369), (109, 37, 39, 339, 359, 376), (110, 29, 48, 342, 358, 378), (111, 39, 29, 343, 363, 370), (112, 35, 36, 348, 370, 379), (113, 93, 84, 349, 370, 380), (114, 90, 92, 350, 368, 382), (115, 24, 15, 352, 367, 380), (116, 50, 42, 354, 369, 388), (117, 90, 70, 355, 373, 388), (118, 42, 33, 358, 379, 393)]
        driverInfo = \
        [(0, 33, 'reputationFocused', 1.0), (1, 49, 'reputationFocused', 1.0), (2, 97, 'greedy', 1.1), (3, 80, 'reputationFocused', 1.1), (4, 60, 'greedy', 1.1), (5, 86, 'greedy', 1.1), (6, 17, 'greedy', 1.0), (7, 7, 'greedy', 0.9), (8, 62, 'reputationFocused', 1.1), (9, 27, 'reputationFocused', 1.0), (10, 97, 'reputationFocused', 1.1), (11, 34, 'rateFocused', 0.9), (12, 76, 'reputationFocused', 1.1), (13, 67, 'reputationFocused', 0.9), (14, 62, 'rateFocused', 0.9)]
        orderQueue = []
        drivers = []
        # INIT ORDERS
        for id, pickup, dropoff, releaseTime, pickupTime, deliverTime in orderInfo:
            orderQueue.append(Order(id, pickup, dropoff, releaseTime, pickupTime, deliverTime, basePay))
        # INIT DRIVERS
        for id, start, policy, driverBehavior in driverInfo:
            driverPolicy = DriverPolicy(policy, policyDict[policy])
            drivers.append(Driver(id, start, driverPolicy, driverBehavior))

        return map, orderQueue, totalMins, drivers, basePay

#PARAMS: testNum, n, m, basePay, numDrivers, durationRange, pickupTimeRange, orderSpawnRate, 
# totalMins, dropoffThreshold=20, deliverTimeWiggleRoom=0

#print(genTest(2, 10, 10, 5, 15, (5, 10), (15, 25), .3, 360))